default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: ccs_development

test:
  <<: *default
  database: ccs_test

production:
  <<: *default
  database: ENV['CLEARDB_DATABASE_URL']