default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: b60c88722ed49e
  password: e726e5c2
  host: us-cdbr-iron-east-04.cleardb.net

development:
  <<: *default
  database: ccs_development

test:
  <<: *default
  database: ccs_test

production:
  <<: *default
  database: ENV['CLEARDB_DATABASE_URL']