# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 0) do

  create_table "semester200001", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200002", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200003", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200004", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200005", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200101", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200102", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200103", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200104", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200105", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200201", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200202", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200203", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200204", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200205", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200301", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200302", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200303", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200304", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200305", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200401", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200402", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200403", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200404", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200405", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200406", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200501", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200502", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200503", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200504", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200505", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200506", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200601", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200602", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200603", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200604", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200605", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200606", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200701", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200702", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200703", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200704", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200705", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200706", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200801", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200802", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200803", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200804", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200805", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200806", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200807", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200901", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200902", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200903", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200904", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200905", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200906", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester200907", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201001", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201002", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201003", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201004", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201005", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201006", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201007", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201101", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201102", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201103", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201104", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201105", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201106", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201107", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201201", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201202", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201203", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201204", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201205", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201206", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201207", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201301", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201302", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201303", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201304", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201305", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201306", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201401", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201402", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201403", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201404", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201405", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

  create_table "semester201501", primary_key: "CRN", force: true do |t|
    t.text    "SUBJ"
    t.integer "CRS"
    t.text    "SEC"
    t.text    "TITLE"
    t.integer "CH"
    t.integer "MAX"
    t.integer "ENR"
    t.integer "AVAIL"
    t.integer "WL"
    t.text    "DAYS"
    t.integer "STIME"
    t.integer "ETIME"
    t.text    "ROOM"
    t.integer "WK"
    t.text    "INSTRUCTOR"
    t.text    "EF"
    t.text    "STARTSON"
  end

end
